import "./globals.css";

export const metadata = {
  title: "NetNerds - Your Favorite Blog in the Devosphere",
  description: "Generated by Mario Juretić",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
