import { Poppins } from "next/font/google";

import Header from "@/components/Header";

import "../globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata = {
  title: "NetNerds - Your Favorite Blog in the Devosphere",
  description: "Generated by Mario Juretić",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="mx-auto max-w-7xl">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
